/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 poly.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/poly.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polybase.geometry} material={materials.rusty} />
      <mesh geometry={nodes.polies.geometry} material={materials['worn-paint-texture']} />
      <mesh geometry={nodes.rings.geometry} material={materials.rusty} />
      <mesh geometry={nodes.chair.geometry} material={materials.woood} />
      <mesh geometry={nodes.ropes.geometry} material={materials['ropes.001']} />
      <mesh geometry={nodes.bucket.geometry} material={materials.initialShadingGroup} />
      <mesh geometry={nodes.scrape.geometry} material={materials['SimplygonCastMaterial.005']} position={[0.415, -0.112, 0.293]} rotation={[-1.63, 0.744, 2.195]} />
      <group position={[0.456, -0.166, 0.256]} rotation={[-1.686, 0.585, 2.851]} scale={0.08}>
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_5_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_5_2.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-0.386, 0.945, -0.022]} rotation={[2.76, 0.343, -1.008]}>
        <mesh geometry={nodes.Object_0.geometry} material={materials.WorkLight} />
        <mesh geometry={nodes.Object_0_1.geometry} material={materials.WorkLightGlass} />
      </group>
      <mesh geometry={nodes['Spray_Bottle_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
      <mesh geometry={nodes['Spray_Bottle_03_-_Default_0_1'].geometry} material={materials['01_-_Default']} />
      <mesh geometry={nodes['Spray_Bottle_03_-_Default_0_2'].geometry} material={materials['02_-_Default']} />
    </group>
  )
}

useGLTF.preload('/poly.glb')
