/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 worker.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/worker.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Object_18">
            <skinnedMesh name="Ch17_Hair_Ch17_hair_0003" geometry={nodes.Ch17_Hair_Ch17_hair_0003.geometry} material={materials.Ch17_body} skeleton={nodes.Ch17_Hair_Ch17_hair_0003.skeleton} />
            <skinnedMesh name="Ch17_Hair_Ch17_hair_0003_1" geometry={nodes.Ch17_Hair_Ch17_hair_0003_1.geometry} material={materials['Ch17_body.001']} skeleton={nodes.Ch17_Hair_Ch17_hair_0003_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/worker.glb')
